stages:
- build
- release

.template: &env-info
  before_script:
  - env | grep -e CARGO -e CI_COMMIT -e CI_PIPELINE
  - bash --version

build:
  <<: *env-info
  stage: build
  script:
  - make init
  - make build

release:
  <<: *env-info
  stage: release
  when: manual
  script:
  - make release
  - docker login -u kirillt -p $DOCKERHUB_TOKEN
  - docker tag supply-chain-ink wivt/supply-chain-ink:$CI_COMMIT_SHORT_SHA 
  - docker tag supply-chain-ink wivt/supply-chain-ink:latest
  - docker push wivt/supply-chain-ink:$CI_COMMIT_SHORT_SHA 
  - docker push wivt/supply-chain-ink:latest
